apiVersion: v1
kind: Secret
metadata:
  name: deposit-service-secrets
  namespace: microservices
type: Opaque
stringData:
  stripe-secret-key: "sk_test_51IAYaILol4iLMIjnDs0z9I96ae9D4vBfwlXi8fIoE57AlxOzvtbKYAt9U5nSAx6F3IPEIZ29mi8LJZ27pyDIyNC1002MLsKDP6"
  stripe-publishable-key: "pk_test_51IAYaILol4iLMIjnVGkKH3C3nuFmTDF20uPnrmLujOjBeQIqk0XXp2Wo3wCTshT44v22BvogjESeGg4J6sV3q8YU00nxLMyoXL"
