apiVersion: v1
kind: Service
metadata:
  name: deposit-service
  namespace: microservices
  labels:
    app: deposit-service
spec:
  type: ClusterIP
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
  selector:
    app: deposit-service
